language: node_js
node_js:
  - '15.14.0'
env:
  - CI=false
  - NODE_ENV=development
script:
  - set -e

  - echo 'installing'
  - npm install --unsafe-perm
  - echo -en 'travis_fold:end:change\\r'

  - echo 'building'
  - npm run build
  - echo -en 'travis_fold:end:change\\r'
