apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greenpress-charts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tikokito123/greenpress.git
    targetRevision: helm-charts
    chart: 
    path: umbrella-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
