"use strict";
exports.__esModule = true;
exports.proxyApiPrefix = exports.privilegedViewingRoles = exports.privilegedEditingRoles = exports.secretsToken = exports.internalServicesSecret = exports.redisUrl = exports.mongoUri = void 0;
exports.mongoUri = process.env.MONGO_URI || 'mongodb://localhost/plugins-service';
exports.redisUrl = process.env.REDIS_URL;
exports.internalServicesSecret = process.env.INTERNAL_SECRET;
exports.secretsToken = process.env.SECRETS_TOKEN || process.env.PLUGINS_SERVICE_SECRET;
exports.privilegedEditingRoles = process.env.PRIVILEGED_EDIT_ROLES ? process.env.PRIVILEGED_EDIT_ROLES.split(',') : ['admin'];
exports.privilegedViewingRoles = process.env.PRIVILEGED_VIEW_ROLES ? process.env.PRIVILEGED_VIEW_ROLES.split(',') : ['plugin', 'editor', 'admin'];
exports.proxyApiPrefix = process.env.PROXY_API_PREFIX || '/api/on';
