apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secrets.fullname" . }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secrets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secrets.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secrets.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.containerPort }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.containerPort }}
          env: 
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: secrets-config
                  key: "SECRETS_MONGODB_URI"
            - name: SECRET
              valueFrom:
                configMapKeyRef:
                  name: secrets-config
                  key: "SECRET"
            - name: INTERNAL_SECRET
              valueFrom:
                configMapKeyRef:
                  name: secrets-config
                  key: "INTERNAL_SECRET"
            - name: IP 
              value: 0.0.0.0
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
