apiVersion: v1
kind: ConfigMap
metadata:
    name: secrets-config
data:
    SECRETS_MONGODB_URI: {{ .Values.global.mongo_service }}
    SECRET: ${SECRETS_SERVICE_SECRET}
    INTERNAL_SECRET: ${INTERNAL_SECRET}


