apiVersion: v1
kind: ConfigMap
metadata:
    name: secrets-config
    namespace: default
data:
    SECRETS_MONGODB_URI: "mongodb://{{ .Release.Name }}-mongodb/greenpress"
    SECRET: ${SECRETS_SERVICE_SECRET}
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    