apiVersion: v1
kind: ConfigMap
metadata:
    name: auth-config
data:
    AUTH_MONGODB_URI: {{ .Values.global.mongo_service }}
    REDIS_URL: {{ .Values.global.redis_url }}
    AUTH_SERVICE_URL: auth

  
    
