apiVersion: v1
kind: ConfigMap
metadata:
    name: assets-config
data:
    ASSETS_MONGODB_URI: "mongodb://{{ .Release.Name }}-mongodb/greenpress"
    REDIS_URL: "{{ .Values.global.redis_url }}"
    SECRETS_SERVICE_URL: "{{ .Release.Name }}-secrets"
    SECRETS_SERVICE_PORT: "9002"
    AUTH_SERVICE_URL: "{{ .Release.Name}}-auth"
    SECRETS_TOKEN: "stamm"
    INTERNAL_SECRET: "staaml"
    IP: "0.0.0.0"