apiVersion: v1
kind: ConfigMap
metadata:
    name: content-config
data:
    CONTENT_MONGODB_URI: "mongodb://{{ .Release.Name }}-mongodb/greenpress"
    REDIS_URL: "{{ .Values.global.redis_url }}"
    AUTH_SERVICE_URL: "{{ .Release.Name }}-auth"
    IP: "0.0.0.0"
