apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
    MONGO_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
    MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
    ASSETS_MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
    AUTH_MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
    CONTENT_MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
    SECRETS_MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
    DRAFTS_MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}@{{ .Values.mongodb.auth.password }}:{{ .Release.Name }}-mongodb/greenpress"
